In [1]:
using LinearAlgebra
# long skinny A example
A = [1 2; 0 5; 6 0]
@show rank(A)

rank(A) = 2


2

In [2]:
b = [1; 2; 3]
F = qr(A) # factorization of F

Q, R = Matrix(F.Q), F.R # extracts Q and R 

([-0.1643989873053573 -0.3620285174334851; 0.0 -0.9302121628499262; -0.986393923832144 0.06033808623891403], [-6.0827625302982185 -0.3287979746107146; 0.0 -5.375117849116603])

In [3]:
y = Q'b
x = R \ y

2-element Vector{Float64}:
 0.49298409728718456
 0.37979420018709065

In [4]:
@show b-A*x #residual

b - A * x = [-0.2525724976613659, 0.10102899906454677, 0.04209541627689273]


3-element Vector{Float64}:
 -0.2525724976613659
  0.10102899906454677
  0.04209541627689273

In [5]:
# the residual should be orthogonal to the columns of A^T 

r = b-A*x
@show norm(A'r) # <- very close to zer 10^-15

norm(A' * r) = 9.75481146369752e-15


9.75481146369752e-15

In [6]:
ep = 1e-7
theta = LinRange(0, 3, 400)
col1 = sin.(theta).^2
col2 = cos.(theta .+ ep).^2
col3 = ones(length(theta))
A = hcat(col1, col2, col3)
xe = [1., 2., 1.]
b = A*xe

400-element Vector{Float64}:
 2.99999999999998
 2.999943465749653
 2.9997738817972888
 2.999491286490054
 2.9990957437298036
 2.998587342958633
 2.9979661991386535
 2.997232452725993
 2.9963862696390384
 2.9954278412209163
 ⋮
 2.9598490109111495
 2.962748986738913
 2.9655443234651533
 2.9682343889944303
 2.9708185750357545
 2.973296297240129
 2.9756669953326904
 2.9779301332393997
 2.9800851992082635

In [ ]:
### Normal Equation Solution
xstar_1 = (A'A) \ (A'b) 
# <- the condition number for A is being squared, the condition number controls the sensitivtiy of the solution. larger condition number means more sensitive to to smaller errors
@show xstar_1

err_1 = norm(xstar_1 - xe)/norm(xe)
@show err_1


xstar_1 = [1.0769230768721778, 2.0769230770796003, 0.9230769230769231]
err_1 = 0.054392829346937996


0.054392829346937996

In [14]:
### QR Solution
F = qr(A)
Q, R = Matrix(F.Q), F.R
y = Q'b
xstar_2 = R \ y
@show xstar_2

err_2 = norm(xstar_2 - xe) / norm(xe)
@show err_2

xstar_2 = [0.9999999962497133, 1.9999999962497135, 1.000000003750286]
err_2 = 2.65185298142961e-9


2.65185298142961e-9

In [13]:
### backslash
xstar_3 = A \ b
@show xstar_3

err_3 = norm(xstar_3 - xe)/norm(xe)
@show err_3

xstar_3 = [0.9999999998372602, 1.9999999998372604, 1.0000000001627405]
err_3 = 1.1507453610876192e-10


1.1507453610876192e-10